//Task 1a
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='EMP';

//Task 1b
ALTER TABLE DEPT ADD CONSTRAINT UN_DNAME UNIQUE(DEPT.DNAME);
ALTER TABLE PURCHASE MODIFY Amount NUMBER(4) NOT NULL;
ALTER TABLE EMP MODIFY EName VARCHAR2(20) NOT NULL;
ALTER TABLE DEPT MODIFY DName VARCHAR2(20) NOT NULL;
